/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUI.java
 *
 * Created on Apr 2, 2010, 12:24:43 PM
 */

/**
 *
 * @author anzalaya
 */
public class GUI extends javax.swing.JFrame {

    /** Creates new form GUI */
    public GUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        board_panel = new javax.swing.JPanel();
        card1_label = new javax.swing.JLabel();
        name1_label = new javax.swing.JLabel();
        game_turn_info_label = new javax.swing.JLabel();
        cards_label = new javax.swing.JLabel();
        name0_label = new javax.swing.JLabel();
        card0_label = new javax.swing.JLabel();
        card2_label = new javax.swing.JLabel();
        name2_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BoardGUI");

        board_panel.setBackground(new java.awt.Color(39, 163, 101));

        game_turn_info_label.setBorder(null);

        javax.swing.GroupLayout board_panelLayout = new javax.swing.GroupLayout(board_panel);
        board_panel.setLayout(board_panelLayout);
        board_panelLayout.setHorizontalGroup(
            board_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(board_panelLayout.createSequentialGroup()
                .addGroup(board_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(board_panelLayout.createSequentialGroup()
                        .addContainerGap(154, Short.MAX_VALUE)
                        .addComponent(name0_label, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                        .addGap(166, 166, 166))
                    .addGroup(board_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(name1_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(board_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(board_panelLayout.createSequentialGroup()
                        .addComponent(card1_label)
                        .addGap(90, 90, 90)
                        .addComponent(card2_label, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(card0_label))
                .addGap(243, 243, 243)
                .addComponent(name2_label)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, board_panelLayout.createSequentialGroup()
                .addGap(363, 363, 363)
                .addComponent(game_turn_info_label)
                .addGap(358, 358, 358))
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, board_panelLayout.createSequentialGroup()
                .addGap(346, 346, 346)
                .addComponent(cards_label)
                .addGap(340, 340, 340))
        );
        board_panelLayout.setVerticalGroup(
            board_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(board_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(board_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(card2_label, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(board_panelLayout.createSequentialGroup()
                        .addComponent(game_turn_info_label)
                        .addGap(160, 160, 160)
                        .addGroup(board_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name1_label, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(card1_label, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(name2_label, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(36, 36, 36)
                .addComponent(card0_label)
                .addGap(139, 139, 139)
                .addGroup(board_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name0_label, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cards_label))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(board_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(board_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel board_panel;
    private javax.swing.JLabel card0_label;
    private javax.swing.JLabel card1_label;
    private javax.swing.JLabel card2_label;
    private javax.swing.JLabel cards_label;
    private javax.swing.JLabel game_turn_info_label;
    private javax.swing.JLabel name0_label;
    private javax.swing.JLabel name1_label;
    private javax.swing.JLabel name2_label;
    // End of variables declaration//GEN-END:variables

}
